import { useMutation, useQueryClient } from "@tanstack/react-query";
import api from "@/features/auth/api/api";
import { Student } from "../types";

// Create Form Data type (omitting id since it's autogenerated)
export type CreateStudentDto = Omit<Student, "id">;

export const createStudent = async (data: CreateStudentDto) => {
  const response = await api.post("/Student/AddNewStudent", data);
  return response.data;
};

export const useCreateStudent = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: createStudent,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["students"] });
    },
  });
};

export const deleteStudent = async (id: number) => {
  const response = await api.delete(`/Student/DeleteStudent`, { params: { id } });
  return response.data;
};

export const useDeleteStudent = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: deleteStudent,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["students"] });
    },
  });
};
